apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tt-clusterrole-minimal-binding
roleRef:
  kind: ClusterRole
  name: tt-clusterrole-minimal
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: tekton-pipeline
    namespace: user14