apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipeline
  namespace: user14
secrets:
- name: dockerhub    # <-- add new secret
- name: tekton-pipeline-dockercfg-kdlwq
- name: tekton-pipeline-token-5wczt
imagePullSecrets:
- name: dockerhub    # <-- add new secret 
- name: tekton-pipeline-dockercfg-kdlwq
- name: tekton-pipeline-token-5wczt