apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
    name: taskrun-git-clone-jc
    namespace: user14
spec:
  taskRef:
    kind: Task
    name: task-git-clone-jc
  params:
    - name: name
      value: task-git-clone-jc