apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-pipeline-jc
  namespace: user14
spec:
  params:
  - name: repo-url
    type: string
    description: URL del repo GIT a clonar
  - name: tag-name
    type: string
    description: The git tag to clone
#  - name: maven-image
#    type: string
#    description:   Image for complile pom
#    default: 'url del constructor de maven'  
  workspaces:
    - name: workspace
#    - name: maven-settings
    - name: empty-dir
  tasks:
    - name: git-clone-jc
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: 'https://github.com/Jcpv/cloud-native-afiliados'
        - name: deleteExisting
          value: "true"
      workspaces:
      - name: output
        workspace: workspace
    - name: list-directory-jc
      runAfter:
        - git-clone-jc
      taskRef:
        kind: Task
        name: list-directory
      workspaces:
      - name: directory
        workspace: workspace

# OMITIR LAS COSAS DE MAVEN
#    - name: maven
#      runAfter:
#        - list-directory-jc
#      taskRef:
#        name: maven