apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-pipeline-jc
  namespace: user14
spec:
  description: |
    Prueba de pipeline
  params:
    - name: url
      value: https://github.com/Jcpv/cloud-native-afiliados
      description: ProbandoGIT-Clone
    workspaces:
    - name: shared-workspace-jc
          persistentVolumeClaim:
        claimName: shared-workspace-jc
#     
#  params:
#    - name: name
#      type: string
  tasks:
    - name: git-clone-jc
      taskRef:
        name: git-clone
      params:
      - name: url
        value: https://github.com/Jcpv/cloud-native-afiliados
      - name: deleteExisting
        value: "true"
      workspaces:
        - name: output
          persistentVolumeClaim:
            claimName: shared-workspace-jc
#      params:
#        - name: name
#          value: $(params.name)      
#    - name: list-directory-jc
#      runAfter:
#        - git-clone-jc
#      taskRef:
#        name: list-directory-jc
#      params:
#        - name: name
#          value: $(params.name)