apiVersion: apps/v1
kind: Pods
metadata:
  name: app-jc-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: app-jc-pod
          image: josecandidop/afiliados2020-user14:v1
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            request:
              memory: "128Mi"
              cpu: "250m"