apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: buildah-run-
spec:
  taskRef:
    name: buildah
  params:
    - name: IMAGE
      # value: 'image-registry.openshift-image-registry.svc:5000/tekton-demo/notificaciones:V5'
      # value: 'docker.io/cafaray/notificaciones:V4'
      value: #    <--- coloca aquí tu tag de imagen completa
    - name: TLSVERIFY
      value: 'false'
    - name: STORAGE_DRIVER
      value: 'vfs'
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: shared-workspace
  serviceAccountName: tekton-pipeline