apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: list-directory-
spec:
  taskRef:
    name: list-directory-jc
  workspaces:
    - name: directory
      persistentVolumeClaim:
        claimName: shared-workspace-jc
