apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: git-pipeline
  namespace: user14
spec:
  params:
  - name: url
    type: string
  tasks:
    - name: git-clone
      taskRef:
        kind: Task
        name: git-clone
      params:
      - name: url
        value: ${params.url}