apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: mascota-pipeline-2g9uod-kubernetes-actions
  generation: 1
  namespace: user15
 
spec:
  params:
    - name: script
      value: >
        kubectl apply -f
        https://raw.githubusercontent.com/luis-cdmx/diplo-cloud-mascota-service/main/resources/manifest/mascota-rest.yaml

        echo "----------"

        kubectl get deployment
  serviceAccountName: pipeline
  taskRef:
    name: kubernetes-actions
  workspaces:
    - emptyDir: {}
      name: kubeconfig-dir
    - emptyDir: {}
      name: manifest-dir










###################

kind: Deployment
apiVersion: apps/v1
metadata:
  name: laravel-app
  namespace: user11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: laravel-app
    spec:
      containers:
        - name: tasks
          image: 'docker.io/janckos/tasks:v7'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600