apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clone-repo-list-dir-jc
  namespace: user14
spec:
  params:
    - name: repo-url
      value: 'https://github.com/Jcpv/cloud-native-afiliados.git'
    - name: tag-name
      value: git-clone-jc-Repo
  pipelineRef:
    name: git-pipeline-jc
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: shared-workspace-jc
    - name: empty-dir
      persistentVolumeClaim:
        claimName: shared-workspace-jc
#status:
#  pipelineSpec:
#    params:
#      - description: URL del repo GIT a clonar
#        name: repo-url
#        type: string
#      - description: The git tag to clone
#        name: tag-name
#        type: string
#    tasks:
#      - name: git-clone-jc
#        params:
#          - name: url
#            value: 'https://github.com/Jcpv/cloud-native-afiliados'
#          - name: deleteExisting
#            value: 'true'
#        taskRef:
#          kind: Task
#          name: git-clone
#        workspaces:
#          - name: output
#            workspace: workspace
#      - name: list-directory-jc
#        runAfter:
#          - git-clone-jc
#        taskRef:
#          kind: Task
#          name: list-directory
#        workspaces:
#          - name: directory
#            workspace: workspace
#    workspaces:
#      - name: workspace
#      - name: empty-dir