apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: kubernetes-actions-
  namespace: user14
spec:
  taskRef:
    name: kubernetes-actions
  params:
    - name: script
      value: |
        kubectl delete deployment afiliados2020-service
        kubectl create deployment afiliados2020 --image=docker.io/josecandidop/afiliados2020:v1
        echo "----------"
        kubectl get deployment
  workspaces:
    - name: kubeconfig-dir
      emptyDir: {}
    - name: manifest-dir
      emptyDir: {}
  serviceAccountName: tekton-pipeline-secret-jc