apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generatedName: buildah-run
  name: prueba-buildah-jc
spec:
  taskRef:
    name: buildah
  params:
    - name: IMAGE
      value: "docker.io/josecandidop/afiliados2020:v1"
    - name: TLSVERIFY
      value: "false"
    - name: STORAGE_DRIVER
      value: "vfs"
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: shared-workspace-jc
  serviceAccountName: tekton-pipeline